#version: 버전 예시 ->'3.3'
version : '1.0'
services:
  db:
    image: mysql
    volumes:
      - ./MYSQL/mysql-init-files/:/docker-entrypoint-initdb.d/
      - ./MYSQL/data/:/var/lib/mysql
    restart: always
    container_name: db_mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
      #- MYSQL_ROOT_PASSWORD=[비밀번호]
    ports:
      - '3333:3306'
    expose:
      - '3333'