#version: 버전 예시 ->'3.3'
version : '3.3'
services:
  db:
    build: ./MYSQL
    volumes:
      - ./MYSQL/mysql-init-files/:/docker-entrypoint-initdb.d/
      - ./MYSQL/data/:/var/lib/mysql
    #restart: always
    container_name: db_mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
      #- MYSQL_ROOT_PASSWORD=[비밀번호]
    ports:
      - '3333:3306'
    networks:
          - blog

  
  frontend:
    build: ./frontend
    volumes:
     - ./frontend:/srv/docker-server
    #restart: always
    container_name: frontend_vue
    ports:
      - '8080:8080'
    networks:
          - blog
networks:
    blog:
        driver: bridge